### ISSUE TITLE
Tutorial Help!

### ISSUE THREAD

**Issue by GiuliaSpi** [3dcitydb/3dcitydb#52]
Hi everyone, really need help. I used FME to convert IFC to citygml. I imported a 3D citygml into 3Dcitymodel, and when I try to export it in KML or also in citygml again, it seems to be 2D!   Why?

**Comment by yaozhihang** [comment]
The exported KML can be 2D if you select the "Footprint" display form. But interestingly, the exported CityGML should never be 2D, since the CityGML-Exporter does not do any 3D -> 2D projection. 

Could you share your 3D CityGML file converted from IFC? It would help us to reproduce and solve the issue. 

PS: The tutorial here (https://github.com/3dcitydb/tutorials) is a good leaning material for getting startet with 3DCityDB.

**Comment by GiuliaSpi** [comment]
Hi, 
really thank you for the help. I practiced with the tutorial, but once i used my case study, I ran into problems. 
At the wetransfer link --> https://we.tl/t-PvKZH6POO1     you can download all my files: 
-IFC
-FME WORKBENCH
-Citygml as FME OUTPUT
-Citygml as 3DcityDB Output. 
-KML after FME
-KML after 3dcitydb

Ps:  my case study is only a single building because I'm also having difficulty understanding how to enrich the database, not being present in the tutorial.  

Thanks

**Comment by yaozhihang** [comment]
Many thanks for sharing the datasets! I've also reproduced the problem. The triangulated surface geometries in the CityGML data from FME are not completely imported into the database. Consequenlty, the exported KML and CityGML data are not correct. 
We'll look into the problem and try to solve it as soon as possible.

**Comment by GiuliaSpi** [comment]
THANK YOU, 
I AM WAITING FOR YOUR USEFUL HELP.

**Comment by GiuliaSpi** [comment]
@yaozhihang 
I found another issue. I can't publish my SPSHG on Google Fusion Tables reported in exercise 5 because Fusion Tables API have been discontinued. they suggest finding alternatives such as BigQuery, Cloud SQL, Maps Platform, and Data Studio. Do you have any suggestions for me? I don't know which one can I use and how.Thank you

**Comment by yaozhihang** [comment]
There are already two alternatives (Google Sheets and PostgreSQL database with a RESTful API). You may get more details from this website: https://github.com/3dcitydb/3dcitydb-web-map/releases

**Comment by GiuliaSpi** [comment]
Ciao @matteomandrile,  ti ringrazio.  
Avevo già tentato di seguire le indicazioni riportate da yaozhihang ma alla fine non sono riuscita ad installare la parte di Google Sheet. Riproverò anche con l'aiuto delle tue indicazioni. 
In ogni caso "una conversione da IFC a CityGML con dati riguardanti le performance energetiche" è esattamente quello che sto investigando anche io. Per farlo ho usato FME ed ho creato un workbench di conversione. Come ho descritto a yaozhihang trasferendo il citygml apparentemente corretto dopo la conversione su 3dcitydb, una volta riesportato perde le sue informazioni 3d. 
@yaozhihang  hypothesis is "The triangulated surface geometries in the CityGML data from FME are not completely imported into the database. Consequently, the exported KML and CityGML data are not correct.
We'll look into the problem and try to solve it as soon as possible." 

So now, I'm waiting for his suggestion, in the meantime, if you are interested I can send you the FME workbench, and maybe we can continue to discuss it, wanting to achieve the same goal 

For now, I'll try again to use Google Sheet.

Thanks

**Comment by GiuliaSpi** [comment]
@matteomandrile 
sono riuscita a seguire tutti i passaggi. ho solo un dubbio sulla parte finale... Nell'immagine riportata ho messo dei numeretti. Se al primo passaggio sono loggout, allora quando clicco sulla chiavetta, riesco a scegliere il mio account in cui ho registrato API Google sheet, ma a seguito dell'accesso a me resta visualizzata la chiavetta e connesso Giulia al primo step, esattamente come vedi nell'immagine. Anche riprovando a cliccare sulla chiave, appare (step 3), attendi un istante... e poi si chiude. Ho provato molte volte, non riesco a raggiungere la situazione in cui al posto della chiavettaa solo loggata anche dentro webclient (come te con MM). Ho sbagliato qualcosa? 

![image](https://user-images.githubusercontent.com/48022581/91029054-9572bd00-e5fe-11ea-9f7c-d42fdd9f030a.png)

**Comment by clausnagel** [comment]
@GiuliaSpi, thanks for reporting the bug with importing your dataset. The current CityGML import assumes a `gml:CompositeSurface` as shell of a solid but your dataset uses a `gml:TriangulatedSurface`. Though being very uncommon, using a `gml:TriangulatedSurface` is technically allowed. A fix is proposed here https://github.com/3dcitydb/importer-exporter/pull/130. You can test the fix by building a new version of the Importer/Exporter following [this guide](https://github.com/3dcitydb/importer-exporter#building).

Some more general guidelines:
* Pick the appropriate issue tracker. For instance, your bug of the Importer/Exporter tool should be reported in the [Importer/Exporter issue tracker](https://github.com/3dcitydb/importer-exporter/issues) rather than here.
* Create one issue per bug or feature request instead of discussing multiple topics in one issue. You can link issues if you think they are related to each other.
* Stick to English language so that others can follow and benefit from the discussions.

**Comment by GiuliaSpi** [comment]
I've really appreciated your suggestions. Thank you.

**Comment by matteomandrile** [comment]
Hello @clausnagel,
Thank you for your fix and suggestion. I will post my previous question in the 3dcitydb-web-map client issue tracker!

**Comment by clausnagel** [comment]
Thanks @GiuliaSpi and @matteomandrile, much appreciated. We will look into your further issues.

**Comment by clausnagel** [comment]
Fixed missing import of TriangulatedSurface with https://github.com/3dcitydb/importer-exporter/pull/130. The fix will be part of the next release of the Importer/Exporter.

**Comment by matteomandrile** [comment]
Hello @clausnagel ,

I built a new version of the Importer/Exporter and it is still throwing errors:
![image](https://user-images.githubusercontent.com/8726351/91943551-0dc33780-ecfd-11ea-86b9-00f534e3e823.png)

I am trying to import a building created by converting an IFC to CityGML, following the same tutorial as @GiuliaSpi, therefore I am also generating triangulated Surfaces:
![image](https://user-images.githubusercontent.com/8726351/91943938-a35ec700-ecfd-11ea-91c9-0d07f9132d15.png)

However if I search in the file the complete XLink reference that is generating the error, it appears that it refers to
 `<app:target>#fme-gen-9e016599-d8c6-4e4c-b097-13892c78010a_16301</app:target>`

In the DB, the building appears to be correctly imported:
![image](https://user-images.githubusercontent.com/8726351/91944509-7ced5b80-ecfe-11ea-905a-c495e5b21d2c.png)
![image](https://user-images.githubusercontent.com/8726351/91944531-870f5a00-ecfe-11ea-991a-fc218f1e3c04.png)
![image](https://user-images.githubusercontent.com/8726351/91944702-cdfd4f80-ecfe-11ea-8b9f-7c0724028ccb.png)

But **the Export file (17 MB) does not show any geometry in FZK**
![image](https://user-images.githubusercontent.com/8726351/91947096-bd99a480-ecff-11ea-850b-99810d066c6a.png)

I attach the "imported" file generated from the IFC->CityGML conversion (FME) and the "exported" file from the imp/exp Tool. 
[test.zip](https://github.com/3dcitydb/3dcitydb/files/5160772/test.zip)

Do you have an idea why this is happening?

**Comment by clausnagel** [comment]
The errors messages are correct because, as the log messages say, your file contains a lot of references that cannot be resolved.

An `<app:target>` must reference an existing surface geometry object. Take your example `<app:target>#fme-gen-9e016599-d8c6-4e4c-b097-13892c78010a_16301</app:target>`. There is no surface geometry with gml:id `fme-gen-9e016599-d8c6-4e4c-b097-13892c78010a_16301` in your file. So the `<app:target>` property points to nowhere and cannot be resolved. Hence the error message. This needs to be fixed in your import dataset.

I also have no issues with visualizing your `Bellevue_LOD2City_export.gml` export dataset with the FZKViewer. I tested with both version 5.3.1 and 6.0 of the software.

**Comment by matteomandrile** [comment]
Thank you for your explanation, I have resolved the issue by changing the CityGML Geometry Setter parameter `City GML Lod Name` from  `lod2Solid`to `lod2MultySurface`.
![image](https://user-images.githubusercontent.com/8726351/92371089-78101980-f0fb-11ea-912e-aac13823cfa9.png)
